using UnityEngine;

public static class AirStripRepository
{
    static AirStripInfo[] airStrips = {
        new AirStripInfo("Oops Field", "Land at your own risk—good luck!"),
        new AirStripInfo("Last Chance Airstrip", "If you miss this one, hope you can swim."),
        new AirStripInfo("Splat Flats", "Come in hot, leave in pieces."),
        new AirStripInfo("Rough Patch Landing", "The runway isn’t the only thing that's rough."),
        new AirStripInfo("Mosquito Ridge Airstrip", "Free blood donation with every landing!"),
        new AirStripInfo("Short Stop Airfield", "Hope your brakes work!"),
        new AirStripInfo("Nope International", "Not international. Not really an airport. But hey, welcome!"),
        new AirStripInfo("Leaky Tank Airstrip", "We fix ‘em, we fuel ‘em, we pray for ‘em."),
        new AirStripInfo("Sputter Strip", "Land. Fix. Take off (hopefully)."),
        new AirStripInfo("Deadstick Depot", "Glide in, roll out, refuel on the way."),
        new AirStripInfo("Redline Runway", "Where your engine blows, and your wallet goes."),
        new AirStripInfo("Wing & A Prayer Airfield", "Emergency landings are our specialty!"),
        new AirStripInfo("Patchwork Airstrip", "We patch planes and pilots alike."),
        new AirStripInfo("Tight Squeeze Airstrip", "If you can land here, you deserve a free oil change!"),
        new AirStripInfo("Backfire Base", "Your plane isn’t the only thing making noise."),
        new AirStripInfo("Busted Prop Airfield", "Prop trouble? We’ve seen worse."),
        new AirStripInfo("Boom & Zoom Airfield", "Fuel up, arm up, and try not to blow up!"),
        new AirStripInfo("Hotshot Haven", "We fix ‘em, fuel ‘em, and load ‘em—what could go wrong?"),
        new AirStripInfo("Kaboom Korner", "Your one-stop shop for gas, ammo, and mild explosions."),
        new AirStripInfo("Last Resort Landing", "If you're here, you probably need all three: fuel, repairs, and firepower."),
        new AirStripInfo("Thud Valley Airstrip", "Named after the sound of bad landings and big bombs."),
        new AirStripInfo("Loosely Secured Ordnance Field", "We swear we keep track of every bomb… most of the time."),
        new AirStripInfo("Full Send Airstrip", "Topped off, locked and loaded, ready for chaos."),
        new AirStripInfo("Fly ‘N’ Die Depot", "Refuel, rearm, and remember your will."),
        new AirStripInfo("Blown Gasket Airfield", "Engines, bombs, pilots… something’s always blowing up!"),
        new AirStripInfo("Short Fuse Strip", "Explosive deals on fuel, repairs, and questionable munitions!"),
        new AirStripInfo("Trenchside Turnpike", "Guaranteed smoother than No Man’s Land!"),
        new AirStripInfo("Baron’s Discount Bombs & Biplanes", "Buy two Sopwith Camels, get a free mustache wax!"),
        new AirStripInfo("Wright Way Repair & Ammo", "Just don’t ask for radar."),
        new AirStripInfo("Ace’s Last Stand", "Out of fuel? Out of bullets? Out of luck."),
        new AirStripInfo("Daring Dash Airstrip", "No parachute? No problem!"),
        new AirStripInfo("Propwash & Powder", "Refuel, rearm, and pretend dogfighting is a good idea!"),
        new AirStripInfo("Top Gassed Airfield", "Highway to the refill zone!"),
        new AirStripInfo("VHS & Victory Landing Strip", "Fuel, bombs, and the latest action flick rentals!"),
        new AirStripInfo("No Man’s Land International", "Now offering radar! (Just kidding, it’s a guy with binoculars and a Walkman.)"),
        new AirStripInfo("The Baron’s Boom Box Base", "Get your refuel, rearm, and rerun of Knight Rider all in one stop!"),
        new AirStripInfo("Lo-Res Landing Strip", "Pixel-perfect landings not required, but recommended."),
        new AirStripInfo("Load\"*\",8,1 Landing Zone", "Now loading… please hold your approach for 12 minutes."),
        new AirStripInfo("Biplane Blitz Base", "Yes, you can fly under bridges. No, you can’t land on them."),
        new AirStripInfo("Crimson Triplane Tavern & Tarmac", "Try to land without exploding, and we’ll buy you a drink!"),
        new AirStripInfo("Flak Magnet Airstrip", "Landing is easy. Getting here in one piece? Not so much."),
        new AirStripInfo("Noisy Skies Repair & Refuel", "Flak explosions: now in full 8-bit mono sound!"),
        new AirStripInfo("Patchwork Propeller Base", "If you made it here, you probably need a new wing."),
        new AirStripInfo("Miracle Mirage Airstrip", "Found by sheer luck—or is it just your C64 saving grace?"),
        new AirStripInfo("Fool’s Luck Fuel Depot", "Against all odds and enemy flak, our runway is as inevitable as your next cassette tape jam."),
        new AirStripInfo("Totally Not Behind Enemy Lines Airstrip", "Ignore the trench warfare outside—we’re totally supposed to be here."),
        new AirStripInfo("Plot Convenience Landing Zone", "Surrounded by hostiles, but we somehow have fuel, bombs, and a snack bar."),
        new AirStripInfo("Against All Odds Airfield", "Flak explosions all around, yet we still have a fully functioning gift shop!"),
        new AirStripInfo("Suspiciously Operational Runway", "Captured? Sabotaged? Nope, we’re just that lucky!"),
        new AirStripInfo("Deus Ex Machina Airbase", "Just when you thought you were doomed—boom! Perfectly placed airstrip."),
        new AirStripInfo("Checkpoint Charlie’s Refuel & Ammo", "Enemy territory? Who cares, we’ve got coffee and bombs!"),
        new AirStripInfo("You Again? Airfield", "Every time you think you’re stranded, surprise! We’re right where you need us."),
        new AirStripInfo("The Last Safe Pixel", "Everything around us is a burning battlefield, but our tarmac is spotless."),
        new AirStripInfo("Secret Enemy-Adjacent Landing Zone", "Nothing to see here, just a completely normal, friendly airstrip in a completely illogical location."),
        new AirStripInfo("We Have No Idea How We Got Here Either Base", "One moment it’s a bombed-out ruin, the next we’ve got a functioning vending machine."),
        new AirStripInfo("Flak Alley Express", "Dodge 300 enemy bullets, and boom—welcome to your local friendly refueling station!"),
        new AirStripInfo("Checkpoint Mirage", "It might look like a bombed-out crater, but surprise! We’ve got a fully stocked ammo depot."),
        new AirStripInfo("The Conveniently Placed Tarmac", "Lost? Outnumbered? Running on fumes? Don’t worry, we’re always exactly where you need us."),
        new AirStripInfo("Against All Logistics Airfield", "Enemy-controlled skies, zero supply lines, yet we have infinite fuel. Don’t ask how."),
        new AirStripInfo("You’re Kidding, Right? Airstrip", "Yes, we exist. No, it doesn’t make sense. Just land already."),
        new AirStripInfo("Totally Secret But Not Really Base", "Deep behind enemy lines, yet we still get fresh milk deliveries every morning!"),
        new AirStripInfo("Refuel & Reload: Enemy Territory Edition", "War is hell, but customer service is our priority!"),
        new AirStripInfo("Plot Device Landing Zone", "When the story needs you to survive, we’ll be right here."),
        new AirStripInfo("Impossible Airfield No. 37", "This is the third ‘completely abandoned’ enemy airfield we’ve taken over this week. Weird, huh?"),
        new AirStripInfo("Canvas Patch Airfield", "We fix holes faster than you can say ‘incoming!’"),
        new AirStripInfo("Stumble Strip", "Where the ground comes up to greet you!"),
        new AirStripInfo("Palette Plane Park", "Limited colors, limitless emergency landings!"),
        new AirStripInfo("Stick-and-String Strip", "Held together by hope, dreams, and questionable engineering!"),
        new AirStripInfo("Gadget Galore Grounds", "If it ain't broke, we can fix that!"),
        new AirStripInfo("Echo Echo Airfield", "Familiarity breeds successful landings!"),
        new AirStripInfo("Cloned Curb Strip", "Our uniformity is unmatched!"),
        new AirStripInfo("Déjà Vu Drome", "If you've seen one, you've seen them all!"),
        new AirStripInfo("Swift Exit Strip", "Come for the fuel, no reason to stay!"),
        new AirStripInfo("Final Flight Fields", "Making the most of your last hoorah!"),
        new AirStripInfo("Bottomless Biplane Depot", "Your aircraft has the cargo capacity of a battleship. Don’t question it."),
        new AirStripInfo("Infinite Ammo Aero Club", "Somehow, your tiny plane carries more rounds than an entire infantry battalion."),
        new AirStripInfo("The Mary Poppins Hangar", "Where do all those bombs come from? Somewhere in your coat pocket, probably."),
        new AirStripInfo("Quantum Cargo Logistics", "Your biplane has the explosive yield of an entire air force. We assume it folds space."),
        new AirStripInfo("Ammo Fairy Airstrip", "No matter how much you shoot, you never run out. Must be magic!"),
        new AirStripInfo("Overloaded But Operational", "It should be impossible to take off with this much ordnance, but here you are."),
        new AirStripInfo("Pocket Dimension Hangar", "Your storage space defies the known laws of physics. We’re proud of you."),
        new AirStripInfo("Copy-Paste Airfield", "Everywhere you go, we’re already there!"),
        new AirStripInfo("Déjà Vu Landing Zone", "Didn't you just land here? No? Well, it sure looks like you did."),
        new AirStripInfo("Carbon Copy Runway", "Different map, same runway. Welcome back!"),
        new AirStripInfo("One Runway Fits All", "From the trenches of Europe to the Arctic tundra—same airstrip, every time!"),
        new AirStripInfo("Ctrl+C, Ctrl+V Airbase", "The developers didn’t have time for variety. Just pretend this is a new place."),
        new AirStripInfo("The Generic Tarmac", "It doesn’t matter where you crash. We’re always here to rebuild the same exact runway!"),
        new AirStripInfo("Mass-Produced Landing Zone", "Factory standard issue! One model, infinite locations."),
        new AirStripInfo("The Infinite Airstrip", "Everywhere is here. Here is everywhere."),
        new AirStripInfo("The Universal Runway", "Why design multiple airfields when we could just make one and call it a day?"),
        new AirStripInfo("Same As Before Airbase", "If you think this looks familiar, congratulations! You have functioning eyes."),
        new AirStripInfo("Top Goon Terminal", "Feel the need... the need for as much speed as you could expect from anything made of wood and canvas."),
        new AirStripInfo("Maiden Flight Meadows", "Live to fly, fly to live"),
        new AirStripInfo("Aces High Haven", "Playing for the high one"),
        new AirStripInfo("Motörs & Pröps", "We serve all the aces"),
        new AirStripInfo("Fuel & Fly Fields", "One stop shopping for the casual aviator"),
        new AirStripInfo("Bombs Away Base", "Burgers, beverages, munitions"),
        new AirStripInfo("Fast and Loose Repairs", "Bombs, fuel, safety. Well, two out of three anyway."),
        new AirStripInfo("Valkyrie Vista", "High-flying heroes take center stage!"),
        new AirStripInfo("Surprise Runway", "One minute, nothing but battlefield. The next, a perfect airstrip appears. Amazing!"),
        new AirStripInfo("Fumes & Hope Airfield", "Out of fuel? We’ve got some… maybe."),
    };

    public static AirStripInfo introLevelStartAirStrip = 
        new AirStripInfo("Ace Academy Airfield", "");

    public static AirStripInfo introLevelEndAirStrip = 
        new AirStripInfo("End of Lesson Airfield", "Welcome back, cadet! Now land before you run out of fuel!");

    public static AirStripInfo GetRandomAirStrip()
    {
        return airStrips[Random.Range(0, airStrips.Length)];
    }
}